[package]
name = "aoc-2020-03"
version = "0.1.0"
authors = ["Jon Terje Tvergrov Kalvatn <j.kalvatn@sportradar.com>"]
edition = "2018"


[[bench]]
name = "bench"
harness = false

[dev-dependencies]
criterion = "0.3"

[dependencies]
aoc-common = { path = "../../aoc-common"}
